# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:
  en: Game Zero ðŸ˜º
  es: Game Zero ðŸ˜º
  ca: Game Zero ðŸ˜º
email: your-email@domain.com
description:
  en: Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description.
  es: Ã‰crivez une super description de votre nouveau site ici. Vous pouvez modifier cette ligne dans _config.yml. Elle apparaÃ®tra dans la balise meta description (pour les rÃ©sultats sur Google) et dans le fil RSS feed.xml.
  ca: More soon
index:
  en:
  es: indice.html
  ca: accueil.html
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://gamezerocat.github.io" # the base hostname & protocol for your site
twitter_username: jrodrigotech
github_username:  jrodrigotech

# Build settings
markdown: kramdown
